# Introduksjon til Python

Python er tolket («interpreted»), ikke kompilert. Man kan gi én og én kommando og få den utført umiddelbart.

## Variabler og typer

Språket bruker dynamisk typing, også kjent som «duck type». Man både definerer og deklarerer en variabel ved å tilordne den en verdi (objekt).

In [1]:
a = 3
b = 3.6
c = 'python'
d = (a == b)
print(a, type(a))
print(b, type(b))
print(c, type(c))
print(d, type(d))
print(a + b, type(a + b))
print(c + str(a))

3 <class 'int'>
3.6 <class 'float'>
python <class 'str'>
False <class 'bool'>
6.6 <class 'float'>
python3


For spesielt interesserte kan det være verdt å merke seg at alt, selv tallkonstanter, er objekter i Python.

In [2]:
print((-3).__abs__())
print((3).__add__(4))

3
7


## Lister, tupler og ordbøker

Python har innebygde datatyper for ulike containere. De viktiste er `list`, `tuple` og `dict`.

### `list` og `tuple`

En `list`er en liste av objekter. De behøver ikke være av samme type. Et `tuple` ligner veldig på en liste, men er konstant og innholdet kan ikke endres.

In [3]:
a = [1, 2 ,3]
print(type(a))
print(a[0])
print(a[-1])
print(a[0:2])
print(a[-1::-1])
a[1] = 'tekst'
print(a)

<class 'list'>
1
3
[1, 2]
[3, 2, 1]
[1, 'tekst', 3]


En liste kan også f.eks. brukes som en stakk.

In [4]:
a.append('42')
print(a)
print(a.pop())
print(a)

[1, 'tekst', 3, '42']
42
[1, 'tekst', 3]


Syntax for `tuple`:

In [5]:
a = 1, 2, 3
print(type(a))
b = (1, 2, 3)
print(type(b))
print(a[0])

<class 'tuple'>
<class 'tuple'>
1


### `dict`

En `dict` er en ordbok («dictionary»), eller det som i mange språk kalles en assosiativ tabell som består av en samling av attributt-verdi par (nøkkel, verdi) hvor hver nøkkel bare opptrer en gang i samlingen.

In [6]:
tlf = {'Frode' : 35191, 'Ivar' : 35277}
print(tlf['Ivar'])
tlf['Erik'] = 35220
print(tlf)

35277
{'Frode': 35191, 'Ivar': 35277, 'Erik': 35220}


## Kontrollstrukturer

De viktigste kontrollstrukturene i Python er `if ... elif ... else`, `for ... in ...` og `while ...`. Blokker i koden defineres utelukkende med innrykk, så det benyttes ikke begin/end, {/} el.l.

In [7]:
for a in range(3):
    print(a)
    if a == 0:
        print('a er null')
    elif a == 1:
        print('a er én')
    else:
        print('a er hverken null eller én')

0
a er null
1
a er én
2
a er hverken null eller én


In [8]:
a = 0
while a < 5:
    print(a)
    a += 1

0
1
2
3
4


En litt artig konstruksjon i Pyhon kalles «list comprehension».

In [9]:
a = [i**2 for i in range(5)]
print(a)

[0, 1, 4, 9, 16]


Løkker kan også avbrytes med `break`, eller tvinges videre med `contine`.

In [10]:
for n in range(2, 10):
...     for x in range(2, n):
...         if n % x == 0:
...             print(n, 'er', x, '*', n//x)
...             break
...     else:
...         # fant ingen faktor
...         print(n, 'er et primtall')

2 er et primtall
3 er et primtall
4 er 2 * 2
5 er et primtall
6 er 2 * 3
7 er et primtall
8 er 2 * 4
9 er 3 * 3


In [11]:
>>> for n in range(2, 10):
...     if n % 2 == 0:
...         print("Fant et partall: ", n)
...         continue
...     print("Fant et oddetall:", n)

Fant et partall:  2
Fant et oddetall: 3
Fant et partall:  4
Fant et oddetall: 5
Fant et partall:  6
Fant et oddetall: 7
Fant et partall:  8
Fant et oddetall: 9


## Funksjoner

Funksjoner defineres med `def ...` og kan ha alt fra ingen til mange returverdier. Hvis det er flere returverdier, returneres de i praksis som et   `tuple`. Parametre overføres som referanser til objekter, så hvis objektene er muterbare, kan en funksjon også endre dem.

In [12]:
def f(x):
    return 2 * x

print(2, f(2))

2 4


In [13]:
def f(x):
    return 2 * x, x**2

print(4, f(4))
x, y = f(4)
print(x)
print(y)

4 (8, 16)
8
16


Det er god praksis å gi alle funksjoner en «docstring» som dokumenterer funksjonen. Det finnes ulike standarder for hvordan disse skal skrives. Vi holder oss til følgende:

1. En kort beskrivelse (en linje) av funksjonen.
2. Eventuelt en litt lengre beskrivende tekst
3. Parametre
4. Returverdier

In [14]:
def dobbel(x):
    """
    Beregner og returnerer den dobbelte verdien.
    
    Det er ikke mye å si om dette, men om man skulle ha lyst,
    kan man skrive en lengre utlegning om temaet dobling her.
    
    Paramters
    ---------
    x : float / int
        Tallet som skal dobles.
    
    Returns
    -------
    float / int
        Den doblede verdien.
    """
    return 2 * x

## Moduler (og pakker)

Funksjoner (og klasser etc.) som man ønsker å gjenbruke, samles gjerne i moduler. En Python-modul er rett og slett bare en fil med Python-kode for funksjoner og eller klasser som kan importeres. Se eksempelet i `modul.py`. Moduler eller funksjoner/klasser fra moduler kan importeres på flere måter.

In [15]:
import modul
print(modul.dobbel(3))

6


In [16]:
import modul as m
print(m.dobbel(3))

6


In [17]:
from modul import dobbel
print(dobbel(3))

6


Dokumentasjonsstrengen brukes til hjelpfunksjonen på ulike måter. For mer omfattende dokumentasjon (i HTML-format etc.) benyttes `pydoc`, og for enda mer omfattende saker finnes `sphinx`.

In [18]:
help(modul.dobbel)

Help on function dobbel in module modul:

dobbel(x)
    Beregner og returnerer den dobbelte verdien.
    
    Det er ikke mye å si om dette, men om man skulle ha lyst,
    kan man skrive en lengre utlegning om temaet dobling her.
    
    Paramters
    ---------
    x : float / int
        Tallet som skal dobles.
    
    Returns
    -------
    float / int
        Den doblede verdien.



In [19]:
dir(modul)

['__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 'dobbel',
 'test_modul',
 'unittest']

## Testing

Det er også god praksis å skrive tester for funksjonene man lager. Én måte å gjøre dette på er å bruke rammeverket `unittest` og lage egne test-klasser som arver fra `unittest.TestCase`. Testene kan kjøres med `python -m unittest <filnavn>`. Eller, om man ønsker en grundigere analyse av hva som er testet, bruk verktøyet `coverage`: `coverage run --source=. -m unittest <filnavn> && coverage html`. Slike oppgaver kan med fordel overlates til `make` med bruk av en `Makefile`.

## Numpy

`numpy` er en modul for beregninger med matriser og vektorer. Vi kommer til å bruke den mye. Den definerer klassen `array`, som er en n-dimensjonal vektor som kan behandles med lineæralgebra-operasjoner.

In [20]:
import numpy as np

print(np.eye(3)) # identitetsmatrisen

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [21]:
print(np.ones(3))
print(np.ones((3, 3)))

[1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [22]:
a = np.random.rand(3, 3)
b = np.linalg.inv(a)
print(a)
print(b)
print(np.dot(a, b)) # matriseprodukt, skal gi identitetsmatrisen

[[0.63577207 0.99187196 0.2027206 ]
 [0.38851484 0.73541301 0.41650485]
 [0.33626492 0.09485272 0.15478535]]
[[ 0.88626638 -1.60141417  3.14843951]
 [ 0.95298294  0.36059462 -2.21841845]
 [-2.50936741  3.25803457  0.98015266]]
[[ 1.00000000e+00  1.37569066e-16 -4.72459539e-17]
 [ 1.99709159e-16  1.00000000e+00  9.96018361e-18]
 [ 3.30661079e-17  4.27242067e-17  1.00000000e+00]]
